// Generated by CoffeeScript 1.4.0
(function() {

  exports.all = function(fun, list) {
    var x, _i, _len;
    for (_i = 0, _len = list.length; _i < _len; _i++) {
      x = list[_i];
      if (!fun(x)) {
        return false;
      }
    }
    return true;
  };

}).call(this);
