// Generated by CoffeeScript 1.4.0
(function() {
  var i, m, _i;

  m = 28433;

  for (i = _i = 1; _i <= 7830457; i = ++_i) {
    m = (m * 2) % 1e10;
  }

  console.log((m + 1) % 1e10);

}).call(this);
