// Generated by CoffeeScript 1.4.0
(function() {
  var euler, i, isLychrel, sum, _i;

  euler = require("euler");

  isLychrel = function(n) {
    var digits, i, tested, _i;
    tested = [];
    for (i = _i = 1; _i <= 50; i = ++_i) {
      digits = euler.digits(n);
      if (euler.isPalindrome(digits) && (i > 1)) {
        return true;
      }
      n += euler.digitsToNumber(digits.reverse());
    }
    return false;
  };

  sum = 0;

  for (i = _i = 1; _i <= 9999; i = ++_i) {
    if (!isLychrel(i)) {
      sum += 1;
    }
  }

  console.log(sum);

}).call(this);
