// Generated by CoffeeScript 1.4.0
(function() {
  var findMax, fs, log, numbers;

  fs = require('fs');

  log = function(_arg) {
    var a, x;
    a = _arg[0], x = _arg[1];
    return x * Math.log(a);
  };

  numbers = function(pair) {
    return pair.split(',').map(function(x) {
      return parseInt(x, 10);
    });
  };

  findMax = function(pairs) {
    var i, index, l, max, pair, _i, _len, _ref, _ref1;
    _ref = [0, 0], max = _ref[0], index = _ref[1];
    _ref1 = pairs.split('\n');
    for (i = _i = 0, _len = _ref1.length; _i < _len; i = ++_i) {
      pair = _ref1[i];
      l = log(numbers(pair));
      if (l > max) {
        max = l;
        index = i;
      }
    }
    return console.log(max, index + 1);
  };

  fs.readFile('base_exp.txt', function(err, data) {
    return findMax(data.toString());
  });

}).call(this);
