// Generated by CoffeeScript 1.4.0
(function() {
  var euler, gcd, i, phi, _i;

  euler = require("euler");

  gcd = function(x, y) {
    var z;
    while (y !== 0) {
      z = x % y;
      x = y;
      y = z;
    }
    return x;
  };

  phi = function(n) {
    var i, sum, _i;
    sum = 0;
    for (i = _i = 1; 1 <= n ? _i < n : _i > n; i = 1 <= n ? ++_i : --_i) {
      if (gcd(i, n) === 1) {
        sum++;
      }
    }
    return sum;
  };

  for (i = _i = 2; _i <= 50; i = ++_i) {
    console.log("n: " + i + ", phi: " + (phi(i)));
  }

}).call(this);
