// Generated by CoffeeScript 1.4.0
(function() {
  var checkDigits, digits, findSmallest, prel, sameDigits;

  prel = require("prelude");

  digits = function(num) {
    var list;
    list = [];
    while (num > 0) {
      list.push(num % 10);
      num = Math.floor(num / 10);
    }
    return list;
  };

  sameDigits = function(dig1, dig2) {
    var _i, _ref, _results;
    dig2.sort();
    return prel.all((function(i) {
      return dig1[i] === dig2[i];
    }), (function() {
      _results = [];
      for (var _i = 0, _ref = dig1.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; 0 <= _ref ? _i++ : _i--){ _results.push(_i); }
      return _results;
    }).apply(this));
  };

  checkDigits = function(i, x, baseDigits) {
    return sameDigits(baseDigits, digits(i * x));
  };

  findSmallest = function() {
    var baseDigits, i;
    i = 9;
    while (true) {
      i++;
      baseDigits = digits(i);
      if (baseDigits[baseDigits.length - 2] === 7) {
        i += Math.pow(10, baseDigits.length) - i;
        continue;
      }
      baseDigits.sort();
      if (prel.all((function(x) {
        return checkDigits(i, x, baseDigits);
      }), [2, 3, 4, 5, 6])) {
        return i;
      }
    }
  };

  console.log(findSmallest());

}).call(this);
