// Generated by CoffeeScript 1.4.0
(function() {
  var c, checkPrimes, combs, concatNumbers, euler, i, prelude, primes, _i, _j, _len;

  euler = require("euler");

  prelude = require("prelude");

  concatNumbers = function(a, b) {
    return euler.digitsToNumber(euler.digits(a).concat(euler.digits(b)));
  };

  checkPrimes = function(candidates) {
    var combs;
    combs = euler.combinations(candidates, 2);
    return prelude.all((function(_arg) {
      var a, b;
      a = _arg[0], b = _arg[1];
      return (euler.isPrime(concatNumbers(a, b))) && (euler.isPrime(concatNumbers(b, a)));
    }), combs);
  };

  primes = [2, 3, 5];

  for (i = _i = 6; _i <= 1000; i = ++_i) {
    if (euler.isPrime(i)) {
      combs = euler.combinations(primes, 3);
      for (_j = 0, _len = combs.length; _j < _len; _j++) {
        c = combs[_j];
        if (checkPrimes(c.concat([i]))) {
          console.log(c.concat([i]));
        }
      }
      primes.push(i);
    }
  }

}).call(this);
